import type { ColorPalette, ColorPaletteInfo, ThemeMood, ThemeMoodInfo } from '../types/settings';

/**
 * Color palette definitions for the Daily Goals App
 * Organized by Mood Categories
 */

// ============================================
// MOOD DEFINITIONS
// ============================================
export const themeMoods: ThemeMoodInfo[] = [
  { id: 'calm', name: 'Calm & Relaxing', description: 'Soothing tones for focus and tranquility' },
  { id: 'energetic', name: 'Energetic & Vibrant', description: 'Bold colors to boost motivation' },
  { id: 'elegant', name: 'Elegant & Sophisticated', description: 'Refined palettes for a premium feel' },
  { id: 'bold', name: 'Bold & Modern', description: 'High contrast for clarity and impact' },
];

// ============================================
// CALM & RELAXING PALETTES
// ============================================

// DEFAULT PALETTE - "Modern Amber"
const defaultPalette = {
  light: {
    primary: '#D68910',
    primaryContainer: '#FDF2E9',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#6E2C00',
    secondary: '#BA4A00',
    secondaryContainer: '#FFDDC1',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#3E1901',
    tertiary: '#2E86C1',
    tertiaryContainer: '#D6EAF8',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#154360',
    accent: '#F1C40F',
    surface: '#FFFFFF',
    surfaceVariant: '#F8F9F9',
    onSurface: '#17202A',
    onSurfaceVariant: '#566573',
    background: '#FDFBF9',
    onBackground: '#17202A',
    error: '#C0392B',
    errorContainer: '#F9E79F',
    onError: '#FFFFFF',
    onErrorContainer: '#641E16',
    outline: '#E5E7E9',
    outlineVariant: '#D7DBDD',
  },
  dark: {
    primary: '#F39C12',
    primaryContainer: '#4E3402',
    onPrimary: '#000000',
    onPrimaryContainer: '#FAD7A0',
    secondary: '#E67E22',
    secondaryContainer: '#5D2E04',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#FFDDC1',
    tertiary: '#5DADE2',
    tertiaryContainer: '#1B4F72',
    onTertiary: '#000000',
    onTertiaryContainer: '#D6EAF8',
    accent: '#F4D03F',
    surface: '#141414',
    surfaceVariant: '#1C1C1C',
    onSurface: '#ECF0F1',
    onSurfaceVariant: '#BDC3C7',
    background: '#050505',
    onBackground: '#ECF0F1',
    error: '#E74C3C',
    errorContainer: '#922B21',
    onError: '#FFFFFF',
    onErrorContainer: '#FADBD8',
    outline: '#2C3E50',
    outlineVariant: '#34495E',
  },
  preview: ['#D68910', '#BA4A00', '#FDFBF9', '#141414'],
};

// OCEAN PALETTE - "Deep Ocean"
const oceanPalette = {
  light: {
    primary: '#0277BD',
    primaryContainer: '#E1F5FE',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#002C3B',
    secondary: '#006064',
    secondaryContainer: '#B2EBF2',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#002C3B',
    tertiary: '#00838F',
    tertiaryContainer: '#B2EBF2',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#002C3B',
    accent: '#4DD0E1',
    surface: '#F1F8E9',
    surfaceVariant: '#E0F7FA',
    onSurface: '#002C3B',
    onSurfaceVariant: '#455A64',
    background: '#E1F5FE',
    onBackground: '#002C3B',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#81D4FA',
    outlineVariant: '#B3E5FC',
  },
  dark: {
    primary: '#4FC3F7',
    primaryContainer: '#01579B',
    onPrimary: '#000000',
    onPrimaryContainer: '#E1F5FE',
    secondary: '#4DD0E1',
    secondaryContainer: '#006064',
    onSecondary: '#000000',
    onSecondaryContainer: '#B2EBF2',
    tertiary: '#80DEEA',
    tertiaryContainer: '#00838F',
    onTertiary: '#000000',
    onTertiaryContainer: '#B2EBF2',
    accent: '#00BCD4',
    surface: '#102027',
    surfaceVariant: '#003642',
    onSurface: '#E1F5FE',
    onSurfaceVariant: '#B0BEC5',
    background: '#001F29',
    onBackground: '#E1F5FE',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#0277BD',
    outlineVariant: '#01579B',
  },
  preview: ['#0277BD', '#006064', '#E1F5FE', '#001F29'],
};

// FOREST PALETTE - "Evergreen"
const forestPalette = {
  light: {
    primary: '#2E7D32',
    primaryContainer: '#E8F5E9',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1B5E20',
    secondary: '#558B2F',
    secondaryContainer: '#F1F8E9',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#33691E',
    tertiary: '#388E3C',
    tertiaryContainer: '#C8E6C9',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#1B5E20',
    accent: '#81C784',
    surface: '#F1F8E9',
    surfaceVariant: '#DCEDC8',
    onSurface: '#1B5E20',
    onSurfaceVariant: '#33691E',
    background: '#F1F8E9',
    onBackground: '#1B5E20',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#A5D6A7',
    outlineVariant: '#C8E6C9',
  },
  dark: {
    primary: '#81C784',
    primaryContainer: '#1B5E20',
    onPrimary: '#000000',
    onPrimaryContainer: '#E8F5E9',
    secondary: '#AED581',
    secondaryContainer: '#33691E',
    onSecondary: '#000000',
    onSecondaryContainer: '#F1F8E9',
    tertiary: '#66BB6A',
    tertiaryContainer: '#2E7D32',
    onTertiary: '#000000',
    onTertiaryContainer: '#C8E6C9',
    accent: '#4CAF50',
    surface: '#1B5E20',
    surfaceVariant: '#224A23',
    onSurface: '#E8F5E9',
    onSurfaceVariant: '#A5D6A7',
    background: '#0D2E10',
    onBackground: '#E8F5E9',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#2E7D32',
    outlineVariant: '#1B5E20',
  },
  preview: ['#2E7D32', '#558B2F', '#F1F8E9', '#0D2E10'],
};

// ZEN PALETTE - "Peaceful Sage"
const zenPalette = {
  light: {
    primary: '#78909C',
    primaryContainer: '#ECEFF1',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#37474F',
    secondary: '#90A4AE',
    secondaryContainer: '#CFD8DC',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#455A64',
    tertiary: '#A5D6A7',
    tertiaryContainer: '#E8F5E9',
    onTertiary: '#1B5E20',
    onTertiaryContainer: '#2E7D32',
    accent: '#B0BEC5',
    surface: '#FAFAFA',
    surfaceVariant: '#F5F5F5',
    onSurface: '#37474F',
    onSurfaceVariant: '#607D8B',
    background: '#FAFAFA',
    onBackground: '#37474F',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#CFD8DC',
    outlineVariant: '#ECEFF1',
  },
  dark: {
    primary: '#B0BEC5',
    primaryContainer: '#455A64',
    onPrimary: '#000000',
    onPrimaryContainer: '#ECEFF1',
    secondary: '#CFD8DC',
    secondaryContainer: '#546E7A',
    onSecondary: '#000000',
    onSecondaryContainer: '#ECEFF1',
    tertiary: '#81C784',
    tertiaryContainer: '#2E7D32',
    onTertiary: '#000000',
    onTertiaryContainer: '#E8F5E9',
    accent: '#90A4AE',
    surface: '#263238',
    surfaceVariant: '#37474F',
    onSurface: '#ECEFF1',
    onSurfaceVariant: '#B0BEC5',
    background: '#1C2529',
    onBackground: '#ECEFF1',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#546E7A',
    outlineVariant: '#455A64',
  },
  preview: ['#78909C', '#90A4AE', '#FAFAFA', '#263238'],
};

// MISTY PALETTE - "Morning Fog"
const mistyPalette = {
  light: {
    primary: '#607D8B',
    primaryContainer: '#E3F2FD',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#263238',
    secondary: '#9E9E9E',
    secondaryContainer: '#F5F5F5',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#424242',
    tertiary: '#B0BEC5',
    tertiaryContainer: '#ECEFF1',
    onTertiary: '#37474F',
    onTertiaryContainer: '#455A64',
    accent: '#CFD8DC',
    surface: '#FAFAFA',
    surfaceVariant: '#F0F4F8',
    onSurface: '#37474F',
    onSurfaceVariant: '#78909C',
    background: '#F5F7FA',
    onBackground: '#37474F',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#E0E0E0',
    outlineVariant: '#EEEEEE',
  },
  dark: {
    primary: '#90A4AE',
    primaryContainer: '#37474F',
    onPrimary: '#000000',
    onPrimaryContainer: '#ECEFF1',
    secondary: '#BDBDBD',
    secondaryContainer: '#616161',
    onSecondary: '#000000',
    onSecondaryContainer: '#F5F5F5',
    tertiary: '#CFD8DC',
    tertiaryContainer: '#546E7A',
    onTertiary: '#000000',
    onTertiaryContainer: '#ECEFF1',
    accent: '#B0BEC5',
    surface: '#1E272C',
    surfaceVariant: '#2C3940',
    onSurface: '#ECEFF1',
    onSurfaceVariant: '#90A4AE',
    background: '#151C20',
    onBackground: '#ECEFF1',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#455A64',
    outlineVariant: '#37474F',
  },
  preview: ['#607D8B', '#9E9E9E', '#F5F7FA', '#1E272C'],
};


// ============================================
// ENERGETIC & VIBRANT PALETTES
// ============================================

// SUNSET PALETTE - "Golden Hour"
const sunsetPalette = {
  light: {
    primary: '#E64A19',
    primaryContainer: '#FBE9E7',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#BF360C',
    secondary: '#FFB300',
    secondaryContainer: '#FFF8E1',
    onSecondary: '#000000',
    onSecondaryContainer: '#FF6F00',
    tertiary: '#F4511E',
    tertiaryContainer: '#FFCCBC',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#BF360C',
    accent: '#FFCA28',
    surface: '#FFF3E0',
    surfaceVariant: '#FFE0B2',
    onSurface: '#3E2723',
    onSurfaceVariant: '#5D4037',
    background: '#FFF8E1',
    onBackground: '#3E2723',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#FFAB91',
    outlineVariant: '#FFCCBC',
  },
  dark: {
    primary: '#FF8A65',
    primaryContainer: '#BF360C',
    onPrimary: '#000000',
    onPrimaryContainer: '#FBE9E7',
    secondary: '#FFD54F',
    secondaryContainer: '#FF6F00',
    onSecondary: '#000000',
    onSecondaryContainer: '#FFF8E1',
    tertiary: '#FFAB91',
    tertiaryContainer: '#D84315',
    onTertiary: '#000000',
    onTertiaryContainer: '#FFCCBC',
    accent: '#FFB74D',
    surface: '#3E2723',
    surfaceVariant: '#4E342E',
    onSurface: '#FFF3E0',
    onSurfaceVariant: '#FFAB91',
    background: '#1A0F0D',
    onBackground: '#FFF3E0',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#BF360C',
    outlineVariant: '#870000',
  },
  preview: ['#E64A19', '#FFB300', '#FFF8E1', '#1A0F0D'],
};

// NEON PALETTE - "Cyberpunk"
const neonPalette = {
  light: {
    primary: '#6200EA',
    primaryContainer: '#ECE0FD',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#310075',
    secondary: '#00B0FF',
    secondaryContainer: '#E1F5FE',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#004D73',
    tertiary: '#D500F9',
    tertiaryContainer: '#FCE4EC',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#6A0080',
    accent: '#CCFF90',
    surface: '#F3E5F5',
    surfaceVariant: '#E1BEE7',
    onSurface: '#310075',
    onSurfaceVariant: '#4A148C',
    background: '#F3E5F5',
    onBackground: '#310075',
    error: '#D50000',
    errorContainer: '#FF8A80',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#B388FF',
    outlineVariant: '#D1C4E9',
  },
  dark: {
    primary: '#B388FF',
    primaryContainer: '#6200EA',
    onPrimary: '#000000',
    onPrimaryContainer: '#ECE0FD',
    secondary: '#40C4FF',
    secondaryContainer: '#0091EA',
    onSecondary: '#000000',
    onSecondaryContainer: '#E1F5FE',
    tertiary: '#EA80FC',
    tertiaryContainer: '#AA00FF',
    onTertiary: '#000000',
    onTertiaryContainer: '#FCE4EC',
    accent: '#CCFF90',
    surface: '#120023',
    surfaceVariant: '#220045',
    onSurface: '#ECE0FD',
    onSurfaceVariant: '#EA80FC',
    background: '#090014',
    onBackground: '#ECE0FD',
    error: '#FF5252',
    errorContainer: '#D32F2F',
    onError: '#000000',
    onErrorContainer: '#FF8A80',
    outline: '#6200EA',
    outlineVariant: '#310075',
  },
  preview: ['#6200EA', '#00B0FF', '#F3E5F5', '#090014'],
};

// TROPICAL PALETTE - "Paradise"
const tropicalPalette = {
  light: {
    primary: '#00BFA5',
    primaryContainer: '#E0F2F1',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#004D40',
    secondary: '#FF6D00',
    secondaryContainer: '#FFE0B2',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#E65100',
    tertiary: '#FFAB00',
    tertiaryContainer: '#FFF8E1',
    onTertiary: '#000000',
    onTertiaryContainer: '#FF6F00',
    accent: '#64FFDA',
    surface: '#E0F7FA',
    surfaceVariant: '#B2DFDB',
    onSurface: '#004D40',
    onSurfaceVariant: '#00695C',
    background: '#E0F2F1',
    onBackground: '#004D40',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#80CBC4',
    outlineVariant: '#B2DFDB',
  },
  dark: {
    primary: '#64FFDA',
    primaryContainer: '#00695C',
    onPrimary: '#000000',
    onPrimaryContainer: '#E0F2F1',
    secondary: '#FFAB40',
    secondaryContainer: '#E65100',
    onSecondary: '#000000',
    onSecondaryContainer: '#FFE0B2',
    tertiary: '#FFD740',
    tertiaryContainer: '#FF6F00',
    onTertiary: '#000000',
    onTertiaryContainer: '#FFF8E1',
    accent: '#1DE9B6',
    surface: '#00332C',
    surfaceVariant: '#004D40',
    onSurface: '#E0F2F1',
    onSurfaceVariant: '#80CBC4',
    background: '#001A16',
    onBackground: '#E0F2F1',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#00695C',
    outlineVariant: '#004D40',
  },
  preview: ['#00BFA5', '#FF6D00', '#E0F2F1', '#00332C'],
};

// FIESTA PALETTE - "Carnival"
const fiestaPalette = {
  light: {
    primary: '#D32F2F',
    primaryContainer: '#FFEBEE',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#B71C1C',
    secondary: '#FFC107',
    secondaryContainer: '#FFF8E1',
    onSecondary: '#000000',
    onSecondaryContainer: '#FF6F00',
    tertiary: '#4CAF50',
    tertiaryContainer: '#E8F5E9',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#1B5E20',
    accent: '#2196F3',
    surface: '#FFFDE7',
    surfaceVariant: '#FFF9C4',
    onSurface: '#3E2723',
    onSurfaceVariant: '#5D4037',
    background: '#FFFDE7',
    onBackground: '#3E2723',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#FFCC80',
    outlineVariant: '#FFE082',
  },
  dark: {
    primary: '#EF5350',
    primaryContainer: '#B71C1C',
    onPrimary: '#000000',
    onPrimaryContainer: '#FFEBEE',
    secondary: '#FFD54F',
    secondaryContainer: '#FF6F00',
    onSecondary: '#000000',
    onSecondaryContainer: '#FFF8E1',
    tertiary: '#81C784',
    tertiaryContainer: '#2E7D32',
    onTertiary: '#000000',
    onTertiaryContainer: '#E8F5E9',
    accent: '#64B5F6',
    surface: '#2E1A1A',
    surfaceVariant: '#3E2723',
    onSurface: '#FFEBEE',
    onSurfaceVariant: '#FFAB91',
    background: '#1A0F0D',
    onBackground: '#FFEBEE',
    error: '#FF5252',
    errorContainer: '#D32F2F',
    onError: '#000000',
    onErrorContainer: '#FFCDD2',
    outline: '#8D6E63',
    outlineVariant: '#6D4C41',
  },
  preview: ['#D32F2F', '#FFC107', '#FFFDE7', '#2E1A1A'],
};


// ============================================
// ELEGANT & SOPHISTICATED PALETTES
// ============================================

// LAVENDER PALETTE - "Royal Amethyst"
const lavenderPalette = {
  light: {
    primary: '#7D3C98',
    primaryContainer: '#F4ECF7',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#4A235A',
    secondary: '#8E44AD',
    secondaryContainer: '#E8DAEF',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#4A235A',
    tertiary: '#AF7AC5',
    tertiaryContainer: '#F5B7B1',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#641E16',
    accent: '#D2B4DE',
    surface: '#FFFFFF',
    surfaceVariant: '#FDFBFD',
    onSurface: '#1A1A1A',
    onSurfaceVariant: '#4A4A4A',
    background: '#FBF8FC',
    onBackground: '#1A1A1A',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#E1BEE7',
    outlineVariant: '#D1C4E9',
  },
  dark: {
    primary: '#BB8FCE',
    primaryContainer: '#4A235A',
    onPrimary: '#000000',
    onPrimaryContainer: '#F4ECF7',
    secondary: '#D2B4DE',
    secondaryContainer: '#5B2C6F',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#E8DAEF',
    tertiary: '#E6B0AA',
    tertiaryContainer: '#784212',
    onTertiary: '#000000',
    onTertiaryContainer: '#F5B7B1',
    accent: '#E1BEE7',
    surface: '#120B16',
    surfaceVariant: '#1F1B24',
    onSurface: '#F3E5F5',
    onSurfaceVariant: '#DAC5E2',
    background: '#0A060C',
    onBackground: '#F3E5F5',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#4A235A',
    outlineVariant: '#381C44',
  },
  preview: ['#7D3C98', '#8E44AD', '#FBF8FC', '#120B16'],
};

// ORCHID PALETTE - "Soft Blossom"
const orchidPalette = {
  light: {
    primary: '#C2185B',
    primaryContainer: '#FCE4EC',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#880E4F',
    secondary: '#D81B60',
    secondaryContainer: '#F8BBD9',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#880E4F',
    tertiary: '#E91E63',
    tertiaryContainer: '#F48FB1',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#880E4F',
    accent: '#FF80AB',
    surface: '#FFFBFC',
    surfaceVariant: '#FFF1F5',
    onSurface: '#2B1B20',
    onSurfaceVariant: '#5D3C47',
    background: '#FFFBFC',
    onBackground: '#2B1B20',
    error: '#B3261E',
    errorContainer: '#F9DEDC',
    onError: '#FFFFFF',
    onErrorContainer: '#410E0B',
    outline: '#F06292',
    outlineVariant: '#F48FB1',
  },
  dark: {
    primary: '#F48FB1',
    primaryContainer: '#880E4F',
    onPrimary: '#000000',
    onPrimaryContainer: '#FCE4EC',
    secondary: '#FF80AB',
    secondaryContainer: '#AD1457',
    onSecondary: '#000000',
    onSecondaryContainer: '#F8BBD9',
    tertiary: '#FF4081',
    tertiaryContainer: '#C2185B',
    onTertiary: '#000000',
    onTertiaryContainer: '#FCE4EC',
    accent: '#F50057',
    surface: '#1F1216',
    surfaceVariant: '#2D1A20',
    onSurface: '#FCE4EC',
    onSurfaceVariant: '#F8BBD9',
    background: '#0F080A',
    onBackground: '#FCE4EC',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#880E4F',
    outlineVariant: '#5D3C47',
  },
  preview: ['#C2185B', '#D81B60', '#FFFBFC', '#0F080A'],
};

// ROSEGOLD PALETTE - "Blush"
const rosegoldPalette = {
  light: {
    primary: '#B76E79',
    primaryContainer: '#FBE9E7',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#5D3A3F',
    secondary: '#D4A5A5',
    secondaryContainer: '#FFEBEE',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#6D4C4C',
    tertiary: '#E8B4B8',
    tertiaryContainer: '#FCE4EC',
    onTertiary: '#5D3A3F',
    onTertiaryContainer: '#880E4F',
    accent: '#F5D0C5',
    surface: '#FFFAF9',
    surfaceVariant: '#FFF5F3',
    onSurface: '#3E2723',
    onSurfaceVariant: '#6D4C4C',
    background: '#FFF8F6',
    onBackground: '#3E2723',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#E8B4B8',
    outlineVariant: '#F5D0C5',
  },
  dark: {
    primary: '#E8B4B8',
    primaryContainer: '#6D4C4C',
    onPrimary: '#000000',
    onPrimaryContainer: '#FBE9E7',
    secondary: '#F5D0C5',
    secondaryContainer: '#8D6E63',
    onSecondary: '#000000',
    onSecondaryContainer: '#FFEBEE',
    tertiary: '#FFCDD2',
    tertiaryContainer: '#AD1457',
    onTertiary: '#000000',
    onTertiaryContainer: '#FCE4EC',
    accent: '#D4A5A5',
    surface: '#2A1F1F',
    surfaceVariant: '#3E2C2C',
    onSurface: '#FBE9E7',
    onSurfaceVariant: '#E8B4B8',
    background: '#1A1212',
    onBackground: '#FBE9E7',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#6D4C4C',
    outlineVariant: '#5D3A3F',
  },
  preview: ['#B76E79', '#D4A5A5', '#FFF8F6', '#2A1F1F'],
};

// CHAMPAGNE PALETTE - "Luxe"
const champagnePalette = {
  light: {
    primary: '#C9A227',
    primaryContainer: '#FFF8E1',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#5D4E37',
    secondary: '#D4AF37',
    secondaryContainer: '#FFFDE7',
    onSecondary: '#000000',
    onSecondaryContainer: '#6D5C3F',
    tertiary: '#E6C35C',
    tertiaryContainer: '#FFF9C4',
    onTertiary: '#5D4E37',
    onTertiaryContainer: '#827717',
    accent: '#F5E6C8',
    surface: '#FFFDF7',
    surfaceVariant: '#FFF9E8',
    onSurface: '#3E3A32',
    onSurfaceVariant: '#6D6555',
    background: '#FFFCF5',
    onBackground: '#3E3A32',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#E6D5A8',
    outlineVariant: '#F5E6C8',
  },
  dark: {
    primary: '#E6C35C',
    primaryContainer: '#6D5C3F',
    onPrimary: '#000000',
    onPrimaryContainer: '#FFF8E1',
    secondary: '#F5E6C8',
    secondaryContainer: '#827717',
    onSecondary: '#000000',
    onSecondaryContainer: '#FFFDE7',
    tertiary: '#FFE082',
    tertiaryContainer: '#9E8B3D',
    onTertiary: '#000000',
    onTertiaryContainer: '#FFF9C4',
    accent: '#D4AF37',
    surface: '#2A2620',
    surfaceVariant: '#3E3830',
    onSurface: '#FFF8E1',
    onSurfaceVariant: '#E6D5A8',
    background: '#1A1814',
    onBackground: '#FFF8E1',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#6D5C3F',
    outlineVariant: '#5D4E37',
  },
  preview: ['#C9A227', '#D4AF37', '#FFFCF5', '#2A2620'],
};


// ============================================
// BOLD & MODERN PALETTES
// ============================================

// BRUTALIST PALETTE - "Swiss International"
const brutalistPalette = {
  light: {
    primary: '#000000',
    primaryContainer: '#E0E0E0',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#121212',
    secondary: '#0055FF',
    secondaryContainer: '#D0E3FF',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#00194A',
    tertiary: '#FF3300',
    tertiaryContainer: '#FFDAD3',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#410001',
    accent: '#00CC66',
    surface: '#FFFFFF',
    surfaceVariant: '#F0F0F0',
    onSurface: '#000000',
    onSurfaceVariant: '#333333',
    background: '#FFFFFF',
    onBackground: '#000000',
    error: '#D32F2F',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#000000',
    outlineVariant: '#555555',
  },
  dark: {
    primary: '#FFFFFF',
    primaryContainer: '#333333',
    onPrimary: '#000000',
    onPrimaryContainer: '#E0E0E0',
    secondary: '#5599FF',
    secondaryContainer: '#003399',
    onSecondary: '#000000',
    onSecondaryContainer: '#D0E3FF',
    tertiary: '#FF8866',
    tertiaryContainer: '#AA2200',
    onTertiary: '#000000',
    onTertiaryContainer: '#FFDAD3',
    accent: '#66FF99',
    surface: '#000000',
    surfaceVariant: '#121212',
    onSurface: '#FFFFFF',
    onSurfaceVariant: '#CCCCCC',
    background: '#000000',
    onBackground: '#FFFFFF',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#FFFFFF',
    outlineVariant: '#AAAAAA',
  },
  preview: ['#000000', '#0055FF', '#FFFFFF', '#000000'],
};

// OBSIDIAN PALETTE - "Carbon Fiber"
const obsidianPalette = {
  light: {
    primary: '#34495E',
    primaryContainer: '#D6DBDF',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1B2631',
    secondary: '#5D6D7E',
    secondaryContainer: '#EBEDEF',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#283747',
    tertiary: '#85929E',
    tertiaryContainer: '#EAEDED',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#34495E',
    accent: '#AEB6BF',
    surface: '#FFFFFF',
    surfaceVariant: '#F2F3F4',
    onSurface: '#17202A',
    onSurfaceVariant: '#566573',
    background: '#F8F9F9',
    onBackground: '#17202A',
    error: '#943126',
    errorContainer: '#F2D7D5',
    onError: '#FFFFFF',
    onErrorContainer: '#641E16',
    outline: '#BDC3C7',
    outlineVariant: '#A6ACAF',
  },
  dark: {
    primary: '#BDC3C7',
    primaryContainer: '#2C3E50',
    onPrimary: '#000000',
    onPrimaryContainer: '#ECF0F1',
    secondary: '#A6ACAF',
    secondaryContainer: '#34495E',
    onSecondary: '#000000',
    onSecondaryContainer: '#D6DBDF',
    tertiary: '#95A5A6',
    tertiaryContainer: '#4D5656',
    onTertiary: '#000000',
    onTertiaryContainer: '#EAEDED',
    accent: '#7F8C8D',
    surface: '#17202A',
    surfaceVariant: '#212F3C',
    onSurface: '#ECF0F1',
    onSurfaceVariant: '#BDC3C7',
    background: '#0B0D0E',
    onBackground: '#ECF0F1',
    error: '#E74C3C',
    errorContainer: '#922B21',
    onError: '#FFFFFF',
    onErrorContainer: '#FADBD8',
    outline: '#34495E',
    outlineVariant: '#283747',
  },
  preview: ['#34495E', '#A6ACAF', '#F8F9F9', '#0B0D0E'],
};

// MIDNIGHT PALETTE - "Deep Space"
const midnightPalette = {
  light: {
    primary: '#1A237E',
    primaryContainer: '#E8EAF6',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#0D1259',
    secondary: '#303F9F',
    secondaryContainer: '#C5CAE9',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#1A237E',
    tertiary: '#3F51B5',
    tertiaryContainer: '#9FA8DA',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#1A237E',
    accent: '#7986CB',
    surface: '#F5F5F5',
    surfaceVariant: '#E8EAF6',
    onSurface: '#1A237E',
    onSurfaceVariant: '#303F9F',
    background: '#FAFAFA',
    onBackground: '#1A237E',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#9FA8DA',
    outlineVariant: '#C5CAE9',
  },
  dark: {
    primary: '#7986CB',
    primaryContainer: '#1A237E',
    onPrimary: '#000000',
    onPrimaryContainer: '#E8EAF6',
    secondary: '#9FA8DA',
    secondaryContainer: '#303F9F',
    onSecondary: '#000000',
    onSecondaryContainer: '#C5CAE9',
    tertiary: '#5C6BC0',
    tertiaryContainer: '#283593',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#9FA8DA',
    accent: '#3F51B5',
    surface: '#0D1259',
    surfaceVariant: '#1A237E',
    onSurface: '#E8EAF6',
    onSurfaceVariant: '#9FA8DA',
    background: '#050824',
    onBackground: '#E8EAF6',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#303F9F',
    outlineVariant: '#1A237E',
  },
  preview: ['#1A237E', '#303F9F', '#FAFAFA', '#050824'],
};

// SLATE PALETTE - "Industrial"
const slatePalette = {
  light: {
    primary: '#455A64',
    primaryContainer: '#CFD8DC',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#263238',
    secondary: '#607D8B',
    secondaryContainer: '#ECEFF1',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#37474F',
    tertiary: '#78909C',
    tertiaryContainer: '#B0BEC5',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#37474F',
    accent: '#90A4AE',
    surface: '#FAFAFA',
    surfaceVariant: '#ECEFF1',
    onSurface: '#263238',
    onSurfaceVariant: '#455A64',
    background: '#F5F5F5',
    onBackground: '#263238',
    error: '#C62828',
    errorContainer: '#FFCDD2',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#B0BEC5',
    outlineVariant: '#CFD8DC',
  },
  dark: {
    primary: '#90A4AE',
    primaryContainer: '#37474F',
    onPrimary: '#000000',
    onPrimaryContainer: '#CFD8DC',
    secondary: '#B0BEC5',
    secondaryContainer: '#455A64',
    onSecondary: '#000000',
    onSecondaryContainer: '#ECEFF1',
    tertiary: '#78909C',
    tertiaryContainer: '#546E7A',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#B0BEC5',
    accent: '#607D8B',
    surface: '#1C2529',
    surfaceVariant: '#263238',
    onSurface: '#ECEFF1',
    onSurfaceVariant: '#90A4AE',
    background: '#0F1518',
    onBackground: '#ECEFF1',
    error: '#EF5350',
    errorContainer: '#8E0000',
    onError: '#FFFFFF',
    onErrorContainer: '#FFCDD2',
    outline: '#455A64',
    outlineVariant: '#37474F',
  },
  preview: ['#455A64', '#607D8B', '#F5F5F5', '#1C2529'],
};

// ============================================
// PALETTE EXPORTS
// ============================================

/**
 * All available color palettes
 */
export const colorPalettes: Record<ColorPalette, { light: typeof defaultPalette.light; dark: typeof defaultPalette.dark; preview: string[] }> = {
  // Calm & Relaxing
  default: defaultPalette,
  ocean: oceanPalette,
  forest: forestPalette,
  zen: zenPalette,
  misty: mistyPalette,
  // Energetic & Vibrant
  sunset: sunsetPalette,
  neon: neonPalette,
  tropical: tropicalPalette,
  fiesta: fiestaPalette,
  // Elegant & Sophisticated
  lavender: lavenderPalette,
  orchid: orchidPalette,
  rosegold: rosegoldPalette,
  champagne: champagnePalette,
  // Bold & Modern
  brutalist: brutalistPalette,
  obsidian: obsidianPalette,
  midnight: midnightPalette,
  slate: slatePalette,
};

/**
 * Color palette info for display in settings, grouped by mood
 */
export const colorPaletteInfoList: ColorPaletteInfo[] = [
  // Calm & Relaxing
  { id: 'default', name: 'Amber (Default)', colors: defaultPalette.preview, mood: 'calm' },
  { id: 'ocean', name: 'Deep Ocean', colors: oceanPalette.preview, mood: 'calm' },
  { id: 'forest', name: 'Evergreen', colors: forestPalette.preview, mood: 'calm' },
  { id: 'zen', name: 'Peaceful Sage', colors: zenPalette.preview, mood: 'calm' },
  { id: 'misty', name: 'Morning Fog', colors: mistyPalette.preview, mood: 'calm' },
  // Energetic & Vibrant
  { id: 'sunset', name: 'Golden Hour', colors: sunsetPalette.preview, mood: 'energetic' },
  { id: 'neon', name: 'Cyberpunk', colors: neonPalette.preview, mood: 'energetic' },
  { id: 'tropical', name: 'Paradise', colors: tropicalPalette.preview, mood: 'energetic' },
  { id: 'fiesta', name: 'Carnival', colors: fiestaPalette.preview, mood: 'energetic' },
  // Elegant & Sophisticated
  { id: 'lavender', name: 'Royal Amethyst', colors: lavenderPalette.preview, mood: 'elegant' },
  { id: 'orchid', name: 'Soft Blossom', colors: orchidPalette.preview, mood: 'elegant' },
  { id: 'rosegold', name: 'Blush', colors: rosegoldPalette.preview, mood: 'elegant' },
  { id: 'champagne', name: 'Luxe', colors: champagnePalette.preview, mood: 'elegant' },
  // Bold & Modern
  { id: 'brutalist', name: 'Swiss (High Contrast)', colors: brutalistPalette.preview, mood: 'bold' },
  { id: 'obsidian', name: 'Carbon', colors: obsidianPalette.preview, mood: 'bold' },
  { id: 'midnight', name: 'Deep Space', colors: midnightPalette.preview, mood: 'bold' },
  { id: 'slate', name: 'Industrial', colors: slatePalette.preview, mood: 'bold' },
];

/**
 * Get palettes grouped by mood
 */
export const getPalettesByMood = (mood: ThemeMood): ColorPaletteInfo[] => {
  return colorPaletteInfoList.filter(palette => palette.mood === mood);
};

/**
 * Get colors for a specific palette and mode
 */
export const getColorsForPalette = (palette: ColorPalette, isDark: boolean) => {
  const selectedPalette = colorPalettes[palette] || colorPalettes.default;
  return isDark ? selectedPalette.dark : selectedPalette.light;
};

// Legacy exports for backward compatibility
export const colors = colorPalettes.default;
