/**
 * Advanced AI Types - Type definitions for advanced AI-powered features
 * Includes AI Goal Coach, Smart Rescheduling, Pattern Detection,
 * Goal Breakdown, Motivational AI, and Predictive Completion
 */

// ============================================================================
// AI Goal Coach Types
// ============================================================================

/**
 * Suggestion generated by AI coach for goal creation
 */
export interface GoalSuggestion {
  /** Suggested goal title */
  title: string;
  /** Optional description */
  description?: string;
  /** Suggested priority */
  priority?: 'low' | 'medium' | 'high';
  /** Suggested category ID */
  categoryId?: string;
  /** Suggested due date in ISO format */
  dueDate?: string;
}

/**
 * Single message in a coach conversation
 */
export interface CoachMessage {
  /** Unique message identifier */
  id: string;
  /** Message sender role */
  role: 'user' | 'assistant';
  /** Message content */
  content: string;
  /** ISO timestamp when sent */
  timestamp: string;
  /** Goal suggestions included in assistant messages */
  suggestions?: GoalSuggestion[];
}

/**
 * Complete coach conversation session
 */
export interface CoachConversation {
  /** Unique conversation identifier */
  id: string;
  /** Associated goal ID if editing existing goal */
  goalId?: string;
  /** Conversation messages */
  messages: CoachMessage[];
  /** ISO timestamp when conversation started */
  createdAt: string;
  /** ISO timestamp of last activity */
  updatedAt: string;
}

// ============================================================================
// Smart Rescheduling Types
// ============================================================================

/**
 * A suggestion to reschedule an overdue goal
 */
export interface RescheduleSuggestion {
  /** ID of the overdue goal */
  goalId: string;
  /** Goal title for display */
  goalTitle: string;
  /** Current/overdue due date */
  currentDueDate: string;
  /** AI-suggested new due date */
  suggestedDueDate: string;
  /** Suggested optimal time (HH:mm) */
  suggestedTime?: string;
  /** Explanation of why this date/time is optimal */
  rationale: string;
  /** Confidence in the suggestion */
  confidence: 'high' | 'medium' | 'low';
  /** Number of days overdue */
  daysOverdue: number;
}

/**
 * User response to a reschedule suggestion
 */
export type RescheduleAction = 'accept' | 'modify' | 'dismiss' | 'snooze';

// ============================================================================
// Pattern Detection Types
// ============================================================================

/**
 * Types of pattern insights AI can detect
 */
export type PatternInsightType =
  | 'streak_risk'         // User at risk of breaking streak
  | 'low_performance_day' // Specific day has low completions
  | 'peak_productivity'   // Identified optimal work times
  | 'category_imbalance'  // Too focused on one category
  | 'overdue_pattern'     // Recurring overdue issues
  | 'time_of_day'         // Best times for certain goals
  | 'workload_warning';   // Too many goals scheduled

/**
 * An AI-detected pattern insight with recommendation
 */
export interface PatternInsight {
  /** Unique insight identifier */
  id: string;
  /** Type of pattern detected */
  type: PatternInsightType;
  /** Short title for the insight */
  title: string;
  /** Detailed message explaining the pattern */
  message: string;
  /** Actionable recommendation */
  actionable: string;
  /** Priority level */
  priority: 'high' | 'medium' | 'low';
  /** ISO timestamp when dismissed (null if active) */
  dismissedAt?: string;
  /** ISO timestamp when generated */
  generatedAt: string;
  /** Related data for the insight */
  metadata?: {
    affectedDays?: number[];
    affectedHours?: number[];
    affectedCategories?: string[];
    streakDays?: number;
  };
}

// ============================================================================
// AI Goal Breakdown Types
// ============================================================================

/**
 * AI-generated subgoal for complex goal breakdown
 */
export interface AIGeneratedSubgoal {
  /** Subgoal title */
  title: string;
  /** Optional description with more details */
  description?: string;
  /** Estimated duration in minutes */
  estimatedDuration?: number;
  /** Suggested order (1-based) */
  order: number;
  /** Whether this is a key milestone */
  isMilestone: boolean;
  /** Suggested due date offset in days from parent goal */
  dueDateOffset?: number;
}

/**
 * Complete goal breakdown result
 */
export interface GoalBreakdown {
  /** Original goal ID */
  goalId: string;
  /** Original goal title */
  goalTitle: string;
  /** AI-generated subgoals */
  subgoals: AIGeneratedSubgoal[];
  /** Total estimated duration in minutes */
  totalEstimatedDuration?: number;
  /** AI explanation of the breakdown approach */
  explanation: string;
  /** Confidence in the breakdown */
  confidence: 'high' | 'medium' | 'low';
}

// ============================================================================
// Motivational AI Types
// ============================================================================

/**
 * Types of motivational messages
 */
export type MotivationalMessageType =
  | 'encouragement'  // General positive reinforcement
  | 'celebration'    // Milestone/achievement celebration
  | 'comeback'       // After missed days/goals
  | 'streak'         // Streak-related motivation
  | 'milestone'      // Personal best or milestone reached
  | 'morning'        // Morning motivation
  | 'evening'        // Evening review/reflection
  | 'category';      // Category-specific motivation

/**
 * Context for generating motivational messages
 */
export interface MotivationContext {
  /** Current streak days */
  streakDays: number;
  /** Goals completed today */
  todayCompleted: number;
  /** Goals remaining today */
  todayRemaining: number;
  /** Recent completion rate (0-100) */
  recentCompletionRate: number;
  /** Days since last completion (0 if completed today) */
  daysSinceLastCompletion: number;
  /** User's dominant category (if any) */
  dominantCategory?: string;
  /** Time of day */
  timeOfDay: 'morning' | 'afternoon' | 'evening' | 'night';
  /** Special occasion (birthday, anniversary, etc.) */
  specialOccasion?: string;
}

/**
 * AI-generated motivational message
 */
export interface MotivationalMessage {
  /** Unique message identifier */
  id: string;
  /** Type of motivation */
  type: MotivationalMessageType;
  /** The motivational message text */
  message: string;
  /** Emoji to display with message */
  emoji: string;
  /** ISO timestamp when generated */
  generatedAt: string;
  /** Context that influenced the message */
  context?: string;
  /** Whether the message has been shown to user */
  shown: boolean;
}

// ============================================================================
// Predictive Completion Types
// ============================================================================

/**
 * Factors influencing completion prediction
 */
export interface PredictionFactor {
  /** Factor name */
  name: string;
  /** Impact on prediction (-100 to +100) */
  impact: number;
  /** Explanation of the factor */
  explanation: string;
}

/**
 * Prediction for goal completion likelihood
 */
export interface CompletionPrediction {
  /** Goal ID this prediction is for */
  goalId: string;
  /** Probability of completion (0-100) */
  probability: number;
  /** Confidence in the prediction */
  confidence: 'high' | 'medium' | 'low';
  /** Factors that influenced the prediction */
  factors: PredictionFactor[];
  /** Suggested actions to improve chances */
  suggestedActions?: string[];
  /** ISO timestamp when calculated */
  calculatedAt: string;
  /** Time until prediction expires (for caching) */
  expiresAt: string;
}

// ============================================================================
// Advanced AI Settings Types
// ============================================================================

/**
 * Settings for advanced AI features
 */
export interface AdvancedAISettings {
  /** Enable AI Goal Coach */
  goalCoachEnabled: boolean;
  /** Enable Smart Rescheduling suggestions */
  smartReschedulingEnabled: boolean;
  /** Enable Pattern Detection insights */
  patternDetectionEnabled: boolean;
  /** Enable AI Goal Breakdown */
  goalBreakdownEnabled: boolean;
  /** Enable Motivational AI messages */
  motivationalEnabled: boolean;
  /** Enable Predictive Completion */
  predictiveEnabled: boolean;
  /** Frequency of pattern analysis */
  patternAnalysisFrequency: 'daily' | 'weekly' | 'realtime';
  /** Show predictions only for high confidence */
  highConfidencePredictionsOnly: boolean;
}

/**
 * Default settings for advanced AI features
 */
export const DEFAULT_ADVANCED_AI_SETTINGS: AdvancedAISettings = {
  goalCoachEnabled: true,
  smartReschedulingEnabled: true,
  patternDetectionEnabled: true,
  goalBreakdownEnabled: true,
  motivationalEnabled: true,
  predictiveEnabled: true,
  patternAnalysisFrequency: 'daily',
  highConfidencePredictionsOnly: false,
};

// ============================================================================
// AI Log Entry Types Extension
// ============================================================================

/**
 * Extended AI operation types for logging
 */
export type AdvancedAILogType =
  | 'goal_coach'
  | 'reschedule_suggestion'
  | 'pattern_insight'
  | 'goal_breakdown'
  | 'motivational'
  | 'prediction';
